// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "https://github.com/whacosta/API-Facturacion-Ecuador/issues"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/": {
            "get": {
                "summary": "Hello World Controller",
                "responses": {}
            }
        },
        "/invoice": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "invoice"
                ],
                "summary": "Generate New Invoice",
                "parameters": [
                    {
                        "description": "New invoice",
                        "name": "invoice",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.InvoiceRequest"
                        }
                    }
                ],
                "responses": {}
            }
        }
    },
    "definitions": {
        "request.Detail": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "discount": {
                    "type": "number"
                },
                "product_code": {
                    "type": "string"
                },
                "tax": {
                    "type": "number"
                },
                "unit_price": {
                    "type": "number"
                }
            }
        },
        "request.InvoiceInfo": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "emission_date": {
                    "type": "string"
                },
                "identification": {
                    "type": "string"
                },
                "identification_type": {
                    "type": "string"
                }
            }
        },
        "request.InvoiceRequest": {
            "type": "object",
            "properties": {
                "details": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/request.Detail"
                    }
                },
                "invoice_info": {
                    "$ref": "#/definitions/request.InvoiceInfo"
                },
                "payments": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/request.Payment"
                    }
                },
                "tax_info": {
                    "$ref": "#/definitions/request.TaxInfo"
                }
            }
        },
        "request.Payment": {
            "type": "object",
            "properties": {
                "payment_form": {
                    "type": "string"
                },
                "sales_time": {
                    "type": "integer"
                },
                "total": {
                    "type": "number"
                },
                "unit_time": {
                    "type": "string"
                }
            }
        },
        "request.TaxInfo": {
            "type": "object",
            "properties": {
                "business_name": {
                    "type": "string"
                },
                "enviroment": {
                    "type": "string"
                },
                "ruc": {
                    "type": "string"
                },
                "sequencial": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "BasicAuth": {
            "type": "basic"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "API Facturación Ecuador",
	Description:      "Esta API, permite enviar a validar comprobantes de manera gratuita.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
